//! Generated Protocol Buffer definitions
//!
//! This module contains the auto-generated gRPC service definitions.
//! Files are generated by tonic-build during compilation.

// Include generated files
// These will be populated after running `cargo build`

#[path = ""]
pub mod chat {
    #![allow(clippy::all)]
    include!("chat.rs");
}

#[path = ""]
pub mod user {
    #![allow(clippy::all)]
    include!("user.rs");
}

#[path = ""]
pub mod common {
    #![allow(clippy::all)]
    include!("common.rs");
}
